/* French overlay for index.html — injected by server.py when UI_LANG=fr.
 *
 * index.html is upstream's file and is never edited here: this script translates the
 * page at runtime, text node by text node, then keeps watching the DOM so everything the
 * SSE stream renders later (verdict labels, lane names, status lines) is translated too.
 * An English string missing from the dictionary simply stays in English — nothing breaks
 * when upstream rewords a sentence; add it below when you notice it.
 *
 * Two tables: DICT for exact strings (whitespace-normalised), PATTERNS for strings that
 * carry numbers or generated fragments. Text generated by the model (readout, rationale,
 * lane summaries) is not translated here: OUTPUT_LANG=fr makes the model write it in
 * French directly.
 */
(function () {
  'use strict';

  const LANES = {
    'Grounded Web': 'Web · réponse sourcée',
    'Semantic Web': 'Web sémantique',
    'Live Index': 'Index live',
    'Deep Research': 'Recherche approfondie',
    'Prediction Market': 'Marché prédictif',
    'Research Literature': 'Littérature scientifique',
  };
  const STANCE = { support: 'soutient', refute: 'réfute', mixed: 'partagé', insufficient: 'insuffisant' };

  const DICT = {
    // ── chrome ──
    'Recommend — Claim Checker': 'Recommend — Vérificateur d’affirmations',
    'PoC · trust layer': 'PoC · couche de confiance',
    'How it works': 'Comment ça marche',
    'Connect via MCP': 'Connecter via MCP',
    'The trust layer, live': 'La couche de confiance, en direct',
    'Every AI will hand you an answer.': 'Toute IA vous donnera une réponse.',
    'We tell you': 'Nous vous disons',
    'what it\'s worth.': 'ce qu’elle vaut.',
    'Retrieval is the easy part. We take the claim apart into the assertions it stands on, weigh independent bodies of evidence against each other,':
      'Chercher est la partie facile. Nous décomposons l’affirmation en assertions qui la portent, confrontons des corpus de preuves indépendants,',
    'attack every conclusion before accepting it': 'attaquons chaque conclusion avant de l’accepter',
    ', and return a score from 0 to 100 with a confidence that falls when the evidence is thin, stale, or argues with itself. You get the reasoning and the sources, not just a verdict.':
      ', et renvoyons un score de 0 à 100 avec une confiance qui baisse quand les preuves sont minces, datées ou contradictoires. Vous obtenez le raisonnement et les sources, pas seulement un verdict.',
    'Check claim': 'Vérifier',
    'include deep research lane (slower)': 'inclure la recherche approfondie (plus lent)',
    'try': 'essayer',
    'e.g. Norway sells more electric cars than petrol cars': 'ex. La Norvège vend plus de voitures électriques que thermiques',
    'Norway sells more electric cars than petrol cars': 'La Norvège vend plus de voitures électriques que thermiques',
    'Electric cars produce less CO2 over their lifetime than petrol cars': 'Une voiture électrique émet moins de CO2 sur sa vie qu’une thermique',
    'Portugal decriminalised the possession of all drugs': 'Le Portugal a dépénalisé la possession de toutes les drogues',
    'Nuclear power causes more deaths per unit of energy than coal': 'Le nucléaire cause plus de morts par unité d’énergie que le charbon',
    'Sugar makes children hyperactive': 'Le sucre rend les enfants hyperactifs',
    'Humans only use 10 percent of their brains': 'Les humains n’utilisent que 10 % de leur cerveau',
    'The Great Wall of China is visible from space with the naked eye': 'La Grande Muraille de Chine est visible depuis l’espace à l’œil nu',
    'Croatia adopted the euro in 2023': 'La Croatie a adopté l’euro en 2023',

    // ── verdict block ──
    'PRELIMINARY': 'PROVISOIRE',
    'FALSE': 'FAUX',
    'TRUE': 'VRAI',
    'Truth score': 'Score de vérité',
    '0 = evidence says false · 50 = genuinely unsettled · 100 = evidence says true':
      '0 = les preuves disent faux · 50 = vraiment indécis · 100 = les preuves disent vrai',
    'Confidence': 'Confiance',
    'Compare with the raw model →': 'Comparer au modèle brut →',
    'Track this daily': 'Suivre chaque jour',
    'Adds this claim to your watchlist. We re-check it every 24h and show the daily move in its score, so you can see the answer change as reality does.':
      'Ajoute cette affirmation à votre liste de suivi. Elle est revérifiée toutes les 24 h et l’évolution quotidienne du score s’affiche, pour voir la réponse bouger avec la réalité.',
    'Show the reasoning ↓': 'Voir le raisonnement ↓',
    'Structured': 'Structuration',
    'Evidence lanes': 'Sources de preuves',
    'Sources': 'Sources',
    'Same claim, asked blind': 'Même affirmation, posée à l’aveugle',
    'The same claim, answered by the raw model from memory alone — no search, no sources — reporting its own confidence. Ours is beside it, grounded in what it actually read.':
      'La même affirmation, répondue par le modèle brut de mémoire seule — sans recherche, sans sources — avec la confiance qu’il s’attribue. La nôtre est à côté, fondée sur ce qui a réellement été lu.',
    'Tracked in this session': 'Suivies dans cette session',
    'Re-check': 'Revérifier',
    'change since previous check': 'variation depuis la vérification précédente',
    'querying…': 'interrogation…',
    'failed': 'échec',
    'not falsifiable': 'non falsifiable',
    'Stream error — is server.py still running?': 'Flux interrompu — server.py tourne-t-il encore ?',
    'Empty claim.': 'Affirmation vide.',

    // server-emitted labels (API values stay English; only the display changes)
    'SUPPORTED': 'CONFIRMÉ', 'LIKELY TRUE': 'PROBABLEMENT VRAI', 'DISPUTED': 'CONTESTÉ',
    'LIKELY FALSE': 'PROBABLEMENT FAUX', 'REFUTED': 'RÉFUTÉ', 'NOT VERIFIABLE': 'NON VÉRIFIABLE',
    'INSUFFICIENT EVIDENCE': 'PREUVES INSUFFISANTES', 'LEANS FALSE': 'PENCHE VERS FAUX',
    'LEANS TRUE': 'PENCHE VERS VRAI', 'UNSETTLED': 'INDÉCIS',
    'Settled question': 'Question tranchée', 'Open question': 'Question ouverte',
    'Contested': 'Contestée', 'Not falsifiable': 'Non falsifiable', 'Unclear': 'Indéterminée',
    'Open question — no evidence settles this yet.': 'Question ouverte — aucune preuve ne la tranche encore.',
    'No lane found evidence solid enough to classify this.': 'Aucune source n’a trouvé de preuve assez solide pour classer cette affirmation.',
    'No lane returned evidence strong enough to decide this.': 'Aucune source n’a renvoyé de preuve assez forte pour décider.',
    'Open question — the event hasn\'t happened yet, so this is a lean from current evidence, not a verdict.':
      'Question ouverte — l’événement n’a pas encore eu lieu : c’est une tendance d’après les preuves actuelles, pas un verdict.',
    'Contested — credible evidence exists on both sides and the question is genuinely unsettled.':
      'Contestée — des preuves crédibles existent des deux côtés et la question n’est vraiment pas tranchée.',
    'Settled question — evidence can decide this, and does.': 'Question tranchée — les preuves peuvent décider, et le font.',
    'Structuring the claim…': 'Structuration de l’affirmation…',
    'Verifying sub-claims…': 'Vérification des sous-affirmations…',
    'Calibrating…': 'Calibration…',
    'Writing the readout…': 'Rédaction de la synthèse…',
    'supported': 'confirmée', 'refuted': 'réfutée', 'unsupported': 'non étayée', 'unchecked': 'non vérifiée',
    'factual': 'factuelle', 'statistical': 'statistique', 'causal': 'causale', 'predictive': 'prédictive', 'opinion': 'opinion',
    'No blind model returned an answer to compare against.': 'Aucun modèle à l’aveugle n’a renvoyé de réponse à comparer.',

    // ── compare modal ──
    'Model · blind': 'Modèle · à l’aveugle',
    'recommend · grounded': 'recommend · sourcé',
    'asking…': 'interrogation…',
    'Raw model, blind': 'Modèle brut, à l’aveugle',
    'recommend, grounded': 'recommend, sourcé',
    'Verdict': 'Verdict',
    'Sources you can open': 'Sources consultables',
    'Independent evidence lanes': 'Sources de preuves indépendantes',
    'Sub-claims verified': 'Sous-affirmations vérifiées',
    'Adversarial review': 'Contre-expertise',
    'If the facts change': 'Si les faits changent',
    'If it were wrong': 'S’il se trompait',
    'none': 'aucune',
    'none — one pass from memory': 'aucune — une passe de mémoire',
    'none for this claim': 'aucune pour cette affirmation',
    'every lane attacked; weight cut where it broke': 'chaque source attaquée ; poids réduit là où elle a cédé',
    'frozen at training time': 'figé à l’entraînement',
    're-checked live, trackable daily': 'revérifié en direct, suivi quotidien possible',
    'sounds exactly this certain': 'paraît exactement aussi sûr',
    'confidence drops and says why': 'la confiance baisse et dit pourquoi',
    'Same verdict.': 'Même verdict.',
    'Not the same evidence.': 'Pas les mêmes preuves.',
    'Different verdict —': 'Verdict différent —',
    'and only one of them is checkable.': 'et un seul des deux est vérifiable.',
    'Agreement is not the product. Anyone can produce this answer; the question is whether you can check it, and what happens on the claim where the model is wrong.':
      'L’accord n’est pas le produit. N’importe qui peut produire cette réponse ; la question est de savoir si vous pouvez la vérifier, et ce qui se passe sur l’affirmation où le modèle se trompe.',
    'The blind model contradicts what the sources actually say.': 'Le modèle à l’aveugle contredit ce que disent réellement les sources.',
    '✓ matches the evidence': '✓ conforme aux preuves',
    '✕ contradicts the evidence': '✕ contredit les preuves',

    // ── how it works ──
    'A claim goes in, six stages run, a score and a confidence come out. Nothing is answered from model memory — every judgement is made against text we fetched for that specific claim. The three marked stages are where the work is ours: retrieval is a commodity anyone can rent, but adjudicating conflicting evidence and knowing what the answer is worth is not.':
      'Une affirmation entre, six étapes s’enchaînent, un score et une confiance sortent. Rien n’est répondu de mémoire — chaque jugement est rendu sur du texte récupéré pour cette affirmation précise. Les trois étapes marquées sont là où le travail est le nôtre : la recherche est une commodité que chacun peut louer, arbitrer des preuves contradictoires et savoir ce que vaut la réponse ne l’est pas.',
    '1 · Structure': '1 · Structurer',
    'The claim is rewritten as one precise, falsifiable sentence and broken into the atomic assertions that must all hold. We also classify it — factual, statistical, causal, predictive or opinion — because that determines how far evidence can take us.':
      'L’affirmation est réécrite en une phrase précise et falsifiable, puis découpée en assertions élémentaires qui doivent toutes tenir. Nous la classons aussi — factuelle, statistique, causale, prédictive ou opinion — car cela détermine jusqu’où les preuves peuvent nous mener.',
    '2 · Query the live web, in parallel': '2 · Interroger le web en direct, en parallèle',
    'We generate several different search angles for the same claim, including one written specifically to surface':
      'Nous générons plusieurs angles de recherche pour la même affirmation, dont un écrit précisément pour faire remonter des preuves',
    'contradicting': 'contradictoires',
    'evidence, then crawl and read the open web across four independent retrieval lanes at once — a grounded-answer lane, a semantic lane, a live search index and a deep-research lane. They run simultaneously, so breadth costs seconds, not minutes. Then the claim\'s type decides what else gets asked: a claim about the future also goes to live prediction markets, where a share price is a probability with real money behind it, and a claim about cause-and-effect or population statistics goes to the peer-reviewed literature, weighted by how much the field actually cites each study. Firing every source at every claim is slower and noisier — knowing which authority settles which kind of question is the point.':
      ', puis lisons le web ouvert via quatre canaux de recherche indépendants à la fois — une réponse sourcée, une recherche sémantique, un index live et une recherche approfondie. Ils tournent simultanément : la largeur coûte des secondes, pas des minutes. Le type d’affirmation décide ensuite de ce qui est demandé en plus : une affirmation sur l’avenir va aussi aux marchés prédictifs, où un prix est une probabilité avec de l’argent réel derrière, et une affirmation de cause à effet ou de statistique de population va à la littérature à comité de lecture, pondérée par le nombre de citations de chaque étude. Lancer toutes les sources sur toutes les affirmations est plus lent et plus bruyant — savoir quelle autorité tranche quel type de question, c’est tout l’enjeu.',
    '3 · Judge each lane on its own evidence': '3 · Juger chaque source sur ses propres preuves',
    'Defensible': 'Défendable',
    'Every lane is scored in isolation, strictly against the pages that lane actually fetched, with background knowledge explicitly forbidden. Each judge reports a stance, a probability, and how decisive its evidence really is — and must name which sources it leaned on, so weak or off-topic pages stop inflating the source count.':
      'Chaque source est notée isolément, strictement sur les pages qu’elle a réellement récupérées, connaissances générales explicitement interdites. Chaque juge rend une position, une probabilité et le caractère décisif réel de ses preuves — et doit nommer les sources sur lesquelles il s’est appuyé, pour que les pages faibles ou hors sujet cessent de gonfler le compte.',
    '4 · Aggregate, and let disagreement cost you': '4 · Agréger, et faire payer le désaccord',
    'Lanes are combined weighted by how decisive each one was. When independent lanes land on opposite sides, confidence drops — that spread is the honest signal that the question is open. A lane that came back empty stays in the denominator, so silence lowers the score instead of quietly disappearing.':
      'Les sources sont combinées, pondérées par leur caractère décisif. Quand des sources indépendantes atterrissent de part et d’autre, la confiance baisse — cet écart est le signal honnête que la question est ouverte. Une source revenue vide reste au dénominateur : le silence baisse le score au lieu de disparaître discrètement.',
    '5 · Calibration review': '5 · Revue de calibration',
    'A final adversarial pass asks whether the verdict is really carried by its evidence, or only by evidence that is adjacent to the claim. It is a one-way ratchet: it can lower confidence, never raise it. Claims about the future or matters of opinion are capped here — absence of reporting is not proof of absence.':
      'Une dernière passe adversariale demande si le verdict est vraiment porté par ses preuves, ou seulement par des preuves adjacentes à l’affirmation. C’est un cliquet à sens unique : il peut baisser la confiance, jamais la relever. Les affirmations sur l’avenir ou les opinions sont plafonnées ici — l’absence de couverture n’est pas une preuve d’absence.',
    '6 · Score, and keep watching': '6 · Noter, et continuer à surveiller',
    'The output is a truth score from 0 to 100 — above 50 leans true — plus a separate confidence saying how much to trust that score at all, and the sources behind it. Claims that aren\'t settled today can be pinned and re-checked daily, so you see the score move as reality does.':
      'La sortie est un score de vérité de 0 à 100 — au-dessus de 50 penche vers vrai — plus une confiance séparée qui dit à quel point faire confiance à ce score, et les sources derrière. Les affirmations non tranchées aujourd’hui peuvent être épinglées et revérifiées chaque jour, pour voir le score bouger avec la réalité.',
    '“But a model is still doing the judging — why trust that?”': '« Mais c’est toujours un modèle qui juge — pourquoi s’y fier ? »',
    'The fair objection, and the reason the architecture looks the way it does. Asking a model to': 'L’objection légitime, et la raison de cette architecture. Demander à un modèle de',
    'recall': 'se souvenir',
    'a fact is where hallucination lives: it answers from compressed memory with no way to know whether it knows. Asking it whether':
      'd’un fait, c’est là que vit l’hallucination : il répond d’une mémoire compressée sans moyen de savoir s’il sait. Lui demander si',
    'this specific text': 'ce texte précis',
    'supports': 'soutient',
    'this specific claim': 'cette affirmation précise',
    'is reading comprehension over material placed in front of it — a far more reliable task, and one you can audit yourself by opening the sources. On top of that we never rely on a single read: several lanes see different evidence, each conclusion is attacked before it is accepted, and disagreement between them lowers the score automatically. The confidence number is the part we are hardening next — fitting it against outcomes we have observed, rather than asking a model how sure it feels.':
      ', c’est de la compréhension de texte sur un document placé devant lui — une tâche bien plus fiable, et que vous pouvez auditer vous-même en ouvrant les sources. De plus nous ne comptons jamais sur une seule lecture : plusieurs sources voient des preuves différentes, chaque conclusion est attaquée avant d’être acceptée, et leur désaccord baisse le score automatiquement. Le chiffre de confiance est la partie que nous durcissons ensuite — en l’ajustant sur des résultats observés, plutôt qu’en demandant au modèle à quel point il se sent sûr.',
    'Every check is logged with its full reasoning trace, which becomes the training corpus for improving the judging over time.':
      'Chaque vérification est journalisée avec sa trace de raisonnement complète, qui devient le corpus d’entraînement pour améliorer le jugement au fil du temps.',

    // ── MCP ──
    'Connect any LLM agent': 'Connecter n’importe quel agent LLM',
    'This whole check is exposed as one MCP tool —': 'Toute cette vérification est exposée comme un seul outil MCP —',
    '. Any agent (Claude, Cursor, your own) can call it and get back the verdict, the confidence, the per-lane breakdown and the sources. Access is':
      '. N’importe quel agent (Claude, Cursor, le vôtre) peut l’appeler et recevoir le verdict, la confiance, le détail par source et les sources. L’accès est',
    'key-gated': 'protégé par clé',
    ': it only answers to a key we issue.': ' : il ne répond qu’à une clé que nous délivrons.',
    'Endpoint': 'Point d’accès',
    'Key': 'Clé',
    'demo key · visible for the PoC only': 'clé de démo · visible pour le PoC seulement',
    'Tool': 'Outil',
    'Any MCP client (JSON config)': 'Tout client MCP (config JSON)',
    'Transport: streamable HTTP (JSON-RPC over': 'Transport : HTTP streamable (JSON-RPC sur',
    '. Without a valid key every call returns 401.': '. Sans clé valide, chaque appel renvoie 401.',
    'Four independent evidence lanes — Grounded Web, Semantic Web, Live Index and Deep Research — queried in parallel. Each lane is scored only against the evidence it actually fetched, never against model memory.':
      'Quatre sources de preuves indépendantes — réponse sourcée, recherche sémantique, index live et recherche approfondie — interrogées en parallèle. Chacune est notée uniquement sur les preuves qu’elle a réellement récupérées, jamais sur la mémoire du modèle.',
  };
  Object.assign(DICT, LANES);

  const n = (x) => String(x);
  const PATTERNS = [
    [/^Querying (\d+) independent sources in parallel…$/, (m) => `Interrogation de ${m[1]} sources indépendantes en parallèle…`],
    [/^— (\d+) pinged simultaneously$/, (m) => `— ${m[1]} interrogées simultanément`],
    [/^(.+?) returned — (\d+) sources, (\w+)$/, (m) => `${LANES[m[1]] || m[1]} : ${m[2]} sources, ${STANCE[m[3]] || m[3]}`],
    [/^(support|refute|mixed|insufficient) · (\d+) sources · ([\d.]+)s$/, (m) => `${STANCE[m[1]]} · ${m[2]} sources · ${m[3]} s`],
    [/^ · (\d+)ms$/, (m) => ` · ${m[1]} ms`],
    [/^(\d+) sources read$/, (m) => `${m[1]} sources lues`],
    [/^(\d+) load-bearing$/, (m) => `${m[1]} déterminantes`],
    [/^(\d+) read, (\d+) load-bearing$/, (m) => `${m[1]} lues, ${m[2]} déterminantes`],
    [/^(\d+) queried in parallel, judged separately$/, (m) => `${m[1]} interrogées en parallèle, jugées séparément`],
    [/^(\d+) checked individually$/, (m) => `${m[1]} vérifiées individuellement`],
    [/^(\d+)% — self-reported, unverifiable$/, (m) => `${m[1]} % — auto-déclarée, invérifiable`],
    [/^(\d+)% — calibrated, falls when lanes disagree$/, (m) => `${m[1]} % — calibrée, baisse quand les sources divergent`],
    [/^(\d+)% self-reported · ([\d.]+)s$/, (m) => `${m[1]} % auto-déclarée · ${m[2]} s`],
    [/^— re-checked daily, (\d+) claims?$/, (m) => `— revérifiées chaque jour, ${m[1]} affirmation${m[1] > 1 ? 's' : ''}`],
    [/^Calibration flag: ([\s\S]*)$/, (m) => `Signal de calibration : ${m[1]}`],
    [/^Challenged: ([\s\S]*)$/, (m) => `Contesté : ${m[1]}`],
    [/^failed: ([\s\S]*)$/, (m) => `échec : ${m[1]}`],
    [/^(✓ matches the evidence|✕ contradicts the evidence) · overconfident by (\d+) pts$/,
      (m) => `${DICT[m[1]]} · surconfiant de ${m[2]} pts`],
    [/^(\d+) of (\d+) evidence lanes agree(?:\. (\d+) returned nothing usable, which lowers confidence)?\. (?:lanes disagree, so confidence is held down|lane spread ([\d.]+), consistent)\.$/,
      (m) => `${m[1]} sources de preuves sur ${m[2]} concordent` +
             (m[3] ? `. ${m[3]} n’ont rien renvoyé d’utilisable, ce qui baisse la confiance` : '') +
             (m[4] ? `. Écart entre sources ${m[4]}, cohérent.` : '. Les sources divergent, la confiance est contenue.')],
    [/^This is a (\S+) claim — evidence can inform it but cannot settle it\. Confidence is capped accordingly\.$/,
      (m) => `Affirmation ${DICT[m[1]] || m[1]} — les preuves peuvent l’éclairer mais pas la trancher. La confiance est plafonnée en conséquence.`],
    [/^(Both models|The blind model) happened to land on the right side here — but asserted it at (\d+)% confidence with zero sources\. On a claim they get wrong, they sound exactly this certain\. Our (\d+)% is backed by (\d+) readable sources\.$/,
      (m) => `${m[1] === 'Both models' ? 'Les deux modèles sont' : 'Le modèle à l’aveugle est'} tombé${m[1] === 'Both models' ? 's' : ''} du bon côté ici — mais avec ${m[2]} % de confiance et zéro source. Sur une affirmation où ${m[1] === 'Both models' ? 'ils se trompent, ils paraissent' : 'il se trompe, il paraît'} exactement aussi sûr. Nos ${m[3]} % reposent sur ${m[4]} sources lisibles.`],
    [/^(Both models|The blind model) contradicts? the evidence — while reporting (\d+)% confidence\. This is the failure mode: fluent, certain, wrong\.$/,
      (m) => `${m[1] === 'Both models' ? 'Les deux modèles contredisent' : 'Le modèle à l’aveugle contredit'} les preuves — tout en annonçant ${m[2]} % de confiance. C’est le mode de défaillance : fluide, certain, faux.`],
    [/^The blind models disagree with each other \((\d+) of (\d+) match the evidence\), yet each reports ~(\d+)% confidence\. Self-reported confidence cannot tell you which one to trust — grounding can\.$/,
      (m) => `Les modèles à l’aveugle se contredisent (${m[1]} sur ${m[2]} conformes aux preuves), et chacun annonce pourtant ~${m[3]} % de confiance. La confiance auto-déclarée ne dit pas lequel croire — l’ancrage dans les sources, si.`],
  ];

  function translate(text) {
    const key = text.replace(/\s+/g, ' ').trim();
    if (!key) return null;
    if (Object.prototype.hasOwnProperty.call(DICT, key)) return DICT[key];
    for (const [re, fn] of PATTERNS) {
      const m = key.match(re);
      if (m) return fn(m);
    }
    return null;
  }

  const SKIP = new Set(['SCRIPT', 'STYLE', 'CODE', 'PRE', 'TEXTAREA', 'INPUT', 'NOSCRIPT']);
  const ATTRS = ['placeholder', 'title', 'aria-label'];

  function translateTextNode(node) {
    const raw = node.nodeValue;
    const out = translate(raw);
    if (out === null || out === raw) return;
    const lead = raw.match(/^\s*/)[0], trail = raw.match(/\s*$/)[0];
    node.nodeValue = lead + out + trail;
  }

  function walk(root) {
    if (root.nodeType === 3) { translateTextNode(root); return; }
    if (root.nodeType !== 1) return;
    for (const a of ATTRS) {
      if (root.hasAttribute(a)) {
        const t = translate(root.getAttribute(a));
        if (t !== null) root.setAttribute(a, t);
      }
    }
    if (SKIP.has(root.tagName)) return;      // attributes yes, contents no (code samples, typed text)
    for (const child of Array.from(root.childNodes)) walk(child);
  }

  function run() {
    document.documentElement.lang = 'fr';
    const t = translate(document.title);
    if (t !== null) document.title = t;
    walk(document.body);
    new MutationObserver((muts) => {
      for (const m of muts) {
        if (m.type === 'characterData') translateTextNode(m.target);
        else if (m.type === 'attributes') walk(m.target);
        else for (const nd of m.addedNodes) walk(nd);
      }
    }).observe(document.body, { childList: true, characterData: true, subtree: true,
                                attributes: true, attributeFilter: ATTRS });
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', run);
  else run();
})();
